location = "local-1"
server_id = 1 # the server to connect to
server_address = "127.0.0.1:8001"
summary_filepath = "./logs/client-1.json"
output_filepath = "./logs/client-1.csv"

[clock]
drift_rate = 1.005         
uncertainty_bound = 0.001 # seconds (1 ms)
sync_freq = 0.001           # Hz

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec = 10
requests_per_sec = 1
read_ratio = 0.25

[[requests]]
duration_sec = 5
requests_per_sec = 10
read_ratio = 0.25

